name: "release-apps"

on:
  push:
    tags:
      - "sample-app*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npx lerna bootstrap
      - run: npx lerna run build
      
      - name: "Upload a Build Artifact"
        uses: actions/upload-artifact@v3.0.0
        with:
          name: dist-release.zip
          path: dist/            
          if-no-files-found: error
          
      - uses: actions/download-artifact@v3
        with:
          name: dist-release.zip
          path: release/dist-release.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            release/*.zip
